### ISSUE TITLE
AudioRecord: start() status -38

### ISSUE THREAD

**Issue by MhtSuthar** [chirp/chirp-connect-react-native#5]
I am using your trial SDK for my application and it awesome :), but sometime in Android device I am facing this type of issue

**AudioRecord: start() status -38**

I am using Native Android Studio SDK(.aar), plz help me how to resolve this issue?

**Comment by joextodd** [comment]
Thanks for the bug report @MhtSuthar 

I cannot find any info on the error code -38. Does this error happen consistently at the same point in your code or does it appear to happen randomly?

**Comment by MhtSuthar** [comment]
It appears randomly

**Comment by joextodd** [comment]
Would you be able to share your code or provide some detailed steps on how to replicate so I can debug further?

**Comment by amod8** [comment]
this happens in my code as well,
It happens when the onPause() of my code gets called:

`protected void onPause() {
  super.onPause();
  chirpConnect.stop();
}
`
I guess the chirpConnect.stop() stops the audio recorder and recorder cannot be initialized again. 
This app will again run normally when the app is destroyed and restarted again.

**Comment by joextodd** [comment]
In your `onResume` method, you should call `chirpConnect.start()` to start the SDK running again. 

I cannot find any info on the -38 error code. If you can supply any more logging information that would help debugging the issue.

**Comment by amod8** [comment]
yup that is called as well and sdk also starts but
AudioRecord: start() status -38
this error occurs

**Comment by amod8** [comment]
Here is the log:

> I/AudioRecord: set(): inputSource 1, sampleRate 44100, format 0x1, channelMask 0x10, frameCount 1792, notificationFrames 0, sessionId 0, transferType 0, flags 0, opPackageName com.example uid -1, pid -1
> **E/AudioRecord: start() status -38**
> D/AudioTrack: set(): streamType -1, sampleRate 44100, format 0x1, channelMask 0x1, frameCount 3536, flags 0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1, cbf 0
> D/AudioTrack: Client defaulted notificationFrames to 1178 for frameCount 3536
> I/android.media.AudioTrack: bufferSizeInBytes:7072 mSampleRate:44100
> W/AudioTrack: Use of stream types is deprecated for operations other than volume control
>               See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
> I/android.media.AudioTrack: play() packageName: com.example.
> V/MyNextActivity: ConnectCallback: onStateChanged 1 -> 3
> V/MyNextActivity: Sdk started

On the first launch of the app, it works fine.  Now in my **onPause**, the chirpconnect is stopped and in **onResume** the sdk again gets started but the error pertains. This problem affects only the mic(recieve), the speaker(send) works perfectly fine.

**Comment by amod8** [comment]
There is no error in this.
Also, as for testing purpose I am using free trial and my license has ended as well. Is this also the cause of the error, that the receiving of sound works in the first attempt only?

**Comment by joextodd** [comment]
This could be the case. Chirp is now distributed as Free to use for any applications with less than 10k monthly active users, so your application should no longer have expired.  Please provide your email or email support@chirp.io and I can look into this for you.

**Comment by amod8** [comment]
Please look at this, this is the error I got with chirpconnect.start(). This error does not occur in first launch.

> V/MyNextActivity: onResume
**E/ConnectError in Start: Your account has been disabled due to an unpaid license. Please contact sales@chirp.io.**
I/AudioRecord: set(): inputSource 1, sampleRate 44100, format 0x1, channelMask 0x10, frameCount 1792, notificationFrames 0, sessionId 0, transferType 0, flags 0, opPackageName com.example
uid -1, pid -1
E/AudioRecord: start() status -38
D/AudioTrack: set(): streamType -1, sampleRate 44100, format 0x1, channelMask 0x1, frameCount 3536, flags 0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1, cbf 0
D/AudioTrack: Client defaulted notificationFrames to 1178 for frameCount 3536
I/android.media.AudioTrack: bufferSizeInBytes:7072 mSampleRate:44100
W/AudioTrack: Use of stream types is deprecated for operations other than volume control
              See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/android.media.AudioTrack: play() packageName: com.example.
V/**MyNextActivity: Sdk started**

my email is amodamatya@gmail.com

**Comment by amod8** [comment]
I updated the sdk, now it works, thank you
